DECLARE @StartDate DATE = '2026-07-01';
DECLARE @EndDate   DATE = '2026-07-31';

;WITH DateList AS
(
    SELECT @StartDate AS SEQ_DATE

    UNION ALL

    SELECT DATEADD(DAY, 1, SEQ_DATE)
    FROM DateList
    WHERE SEQ_DATE < @EndDate
),
SeqKeyList AS
(
    SELECT 12 AS SEQ_KEY
    UNION ALL SELECT 31
    UNION ALL SELECT 51
    UNION ALL SELECT 61
    UNION ALL SELECT 71
)
INSERT INTO MST_SEQ
(
    SEQ_ID,
    SEQ_VALUE
)
SELECT
    K.SEQ_KEY * 1000000
        + CONVERT(DECIMAL(8, 0), CONVERT(VARCHAR(8), D.SEQ_DATE, 112)) AS SEQ_ID,
    10000 AS SEQ_VALUE
FROM DateList D
CROSS JOIN SeqKeyList K
WHERE NOT EXISTS
(
    SELECT 1
    FROM MST_SEQ M
    WHERE M.SEQ_ID =
        K.SEQ_KEY * 1000000
        + CONVERT(DECIMAL(8, 0), CONVERT(VARCHAR(8), D.SEQ_DATE, 112))
)
OPTION (MAXRECURSION 100);